name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '30 5,17 * * *'
 

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Prepare the environment
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # Instalando as bibliotecas
    - name: Install requirements
      run: |-
        python -m pip install pandas
        python -m pip install requests
    - name: Executar o script
      run: python exercicio1.py 
    # Step 3: Commit and push
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git push
